name: Cucumber CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-node-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-node-
      name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'adopt'
            server-id: github
            settings-path: ${{ github.workspace }}
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: test gradle
        run: |
          cd gradle
          ./gradlew test || true

      - name: Zip report files
      if: always()
      run: zip -r reports.zip reports

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports.zip
          path: ${{ github.workspace }}/reports.zip